### ISSUE TITLE
Integer literals with leading zeros in Lexer

### ISSUE THREAD

**Issue by larsk21** [larsk21/compiler-minijava#15]
Having something like `int x = 01;` results in

```
non-zero integer literal with leading zero
```

while it should yield two integer literals `0` and `1`.

**Comment by g4rgoil** [comment]
Yes, I thought this was how the lexer was supposed to behave. It is a pretty straight forward fix though.

**Comment by g4rgoil** [comment]
See PR #17

**Comment by larsk21** [comment]
> See PR #17

You can use closing keywords in a PR to link an issue to it (this will automatically close the issue when the PR is merged).
