### ISSUE TITLE
Large integer literals in Lexer

### ISSUE THREAD

**Issue by larsk21** [larsk21/compiler-minijava#16]
The value of an integer should not be restricted in the Lexer, therefore any integer (that is reasonable to store in the memory, ~1000 characters at least) should be accepted by the Lexer.

Current behaviour: `error: [...] integer literal too large`

**Comment by g4rgoil** [comment]
We'll need to change our token to make this work.

**Comment by larsk21** [comment]
True, what is the best way to fix this? Re-adding the stringValue and using it for the lexed characters?
