### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by larsk21** [larsk21/compiler-minijava#22]
This is more of a general issue. We should think about performance in all phases of our compiler.

**Comment by g4rgoil** [comment]
Looking at the Speedcenter test results, our compiler seems to be quite competitive when compared to the other groups (at least for now).

**Comment by larsk21** [comment]
Possible optimizations:

- [ ] use a ring buffer instead of a linked list for the lookahead

**Comment by 0xNB** [comment]
We should probably log how many of which operations get normally performed during a compiler run and choose a fitting data structure. 

I propose that we also add some benchmark checks for maven that don't run with normal unit tests but can be triggered if we want to

**Comment by larsk21** [comment]
Is manual logging of operations necessary? Why not use some kind of Java Profiler to analyze our program?
