### ISSUE TITLE
Change `line` and `column` to `sourceLocation : SourceLocation`

### ISSUE THREAD

**Issue by larsk21** [larsk21/compiler-minijava#42]
Since we have a new data class, we should use it to make our code more readable. Possible locations for this change are `Token` and `AstNode`.

**Comment by 0xNB** [comment]
![grafik](https://user-images.githubusercontent.com/14185207/141688932-6f2d7fce-9af5-4599-ac97-ff402b8b496d.png)

Mir ist das relativ egal, ich würde aber auch nicht unbedingt eine Datenstruktur benutzen

**Comment by larsk21** [comment]
Perhaps, it's just quite lengthy to write `new SourceLocation(someTokenOfSomeClass.getLine(), someTokenOfSomeClass.getColumn())` again and again.
