### ISSUE TITLE
Use `ErrorHandler` in detailed name/type analysis

### ISSUE THREAD

**Issue by larsk21** [larsk21/compiler-minijava#60]
It would improve the detailed name and type analysis, if we were able to report more than one error. The necessary changes include moving from exception throwing to collecting errors (easy), as well as taking into account that reporting an error would not end the method immediately, potentialy causing follow-up errors (more complicated).

**Comment by 0xNB** [comment]
This was the thing with anchor sets we need to introduce on the parser level to be able to handle panic mode. If we have time at the end of this assignment I'd say we can try to implement some anchor sets. 

Also Phase 1 and 3 already implement the ErrorHandler interface, we'd just have to change one line in Phase 2 to use this as well.

**Comment by larsk21** [comment]
Detailed name/type analysis is the last part of phase 3, where we have not yet implemented collecting multiple errors. It's not as hard as for the parser, I just have to look over all the methods I wrote in the AST visitor.
